### ISSUE TITLE
Karabiner-Elements Breaks Ctrl-Esc?

### ISSUE THREAD

**Issue by SolusCado** [pqrs-org/KE-complex_modifications#112]
I've mapped Ctrl-Esc in MacOS' System Preferences to open Launchpad, and it works - until I open Karabiner Elements. Even with NO MAPPINGS enabled, Karabiner Elements prevents the Ctrl-Esc keyboard shortcut from opening Launchpad.

Any idea why?

**Comment by smlewis** [comment]
I'm really glad you didn't post this question maliciously, because I totally just tried Ctrl-Esc to see what would happen - just like in the old days when people would troll with Alt-F4 on Windows...

(It does nothing on my system either with Elements active; I've never tried it without Elements active).

**Comment by SolusCado** [comment]
:) Haha... It didn't even occur to me to pull something like that. But it only does something if you've mapped the shortcut in System Preferences. I've mapped the shortcut in question (open Launchpad) to Option-L instead as a workaround, which I then use Karabiner to remap a single press of the Command key to. The idea is to emulate the behavior you get in Windows: a single press of the Command key, like a single press of the Windows key, open the "start menu" - while Ctrl-Esc does the same thing.
________________________________
