### ISSUE TITLE
Can you please help me bind the help key

### ISSUE THREAD

**Issue by jdamour98** [pqrs-org/KE-complex_modifications#152]
In events view, my help key produces 

```
eventType:KeyDown         code:0x72       name:help            flags:Fn                                 misc:
eventType:KeyUp           code:0x72       name:help            flags:Fn                                 misc:
```

so, I made the following rule

```json
{
          "type": "basic",
          "from": {
            "key_code": "help",
            "modifiers": {
              "mandatory": [
                "Fn"
              ]
            }
          },
          "to": [
            {
              "key_code": "play_or_pause",
            }
          ]
        }
```

But it doesn't seem to work, regardless of whether i include the fn flag or not. Can ya point me in the right direction? Thanks!

**Comment by yqrashawn** [comment]
Fn should be fn in lowercase. Could that be the reason why it won't work?

**Comment by jdamour98** [comment]
Thats originally what i tried. Just tried again to confirm, no luck. Event viewer is still output "help + Fn" when pressed

**Comment by yqrashawn** [comment]
I don't have the help key on my keyboard, so I tried another key + fn bind to `play_or_pause` and it works fine.
```
                            {
                                "from": {
                                    "key_code": "9",
                                    "modifiers": {
                                        "mandatory": [
                                          "fn"
                                        ]
                                    }
                                },
                                "to": [
                                    {
                                        "key_code": "play_or_pause"
                                    }
                                ],
                                "type": "basic"
                            },
```
May be it have something to do with the help? What keyboard are you using?

**Comment by jdamour98** [comment]
It could be the keyboard i suppose... Its the Drevo Culibur, a board made in china. The keycap says insert. However, I'm going off the output of the event viewer, so i thought if i use whatever the output key code is, it would work fine. Instead of insert, event viewer is showing "help". Let me try th einsert keycode.

**Comment by jdamour98** [comment]
Not working... will the hex code work in the json? This is the code coming from the board and os:

kVK_Help = 0x72

**Comment by kzsh** [comment]
I don't believe the hex or kVK will work in the json config.

I did a little testing of this, using the only external keyboard I have which has an `insert` key that sends `0x72 (help)`.  At first I thought the issue was that `help` was one of the special keys that has an implicit `fn` in its invocation, but after successfully remapping `home` or `end` to `play_or_pause`, I think it's an issue isolated to the help key specifically.

**Comment by evturn** [comment]
@kzsh what key(s) are you trying to bind to the `help` key?

**Comment by kzsh** [comment]
Initially, I was trying to bind `play_or_pause` as initially attempted by @jdamour98, but when that didn't work, I tried simple keys like `a` just to start ruling out odd behavior around special keys.  That didn't work, either though.  The odd thing is that I can get exactly the requisite mapping if I use `home`, or `end` or `page_up` or `page_down`.
I tried these other keys because they seem to fall in to the same category of keys that have an implicit `fn` modifier built in.  I've attached screen captures of the event viewer below first without any special bindings, then with binding both `home` and `help` to `play_or_pause`.

### Without bindings

<img width="579" alt="screen shot 2017-10-19 at 9 29 08 am" src="https://user-images.githubusercontent.com/1041312/31773392-9b83075e-b4b0-11e7-8472-7872b8dab8be.png">

### With `home` and `help` bound to `play_or_pause`

<img width="621" alt="screen shot 2017-10-19 at 9 28 28 am" src="https://user-images.githubusercontent.com/1041312/31773398-9e96081a-b4b0-11e7-9380-62ba9aac2f60.png">

**Comment by evturn** [comment]
Looks like Macs stopped supporting the `help` key since OSX 10.6 Snow Leopard with applications containing their own Help menu as a matter of convention. From what it looks like `command` + `shift` + `slash` aka `⌘?`

**Comment by jdamour98** [comment]
I'm trying to bind the key of a bluetooth (PC) keyboard though, changing my key or key combination isn't the goal.

**Comment by tekezo** [comment]
The `help` key's HID usage page is `insert`.
Please specify `insert` key to from key.

![171021-0001](https://user-images.githubusercontent.com/659178/31832812-4f381516-b603-11e7-90ee-c0ffaf0d9ff1.png)

**Comment by kzsh** [comment]
@jdamour98 are you able to get the binding working the way you want with the `insert` key as indicated in the last comment?

**Comment by jdamour98** [comment]
Yes I did, thank you for the help! I should have posted sooner. It works as shown in the previous comment. Consider updating event viewer to print Help/Insert for 0x72

**Comment by yqrashawn** [comment]
Seems we can close this.
