### ISSUE TITLE
switch language with Option+Shift or Cmd+Shift

### ISSUE THREAD

**Issue by Thaina** [pqrs-org/KE-complex_modifications#196]
Is it possible?

**Comment by bingocaller** [comment]
Do you mean the OS language or the keyboard layout/language?
The former is quite complicated because it would require running `languagesetup`, choosing a language, _and_ restarting the system.
The latter can be [set natively in your System Preferences.](http://osxdaily.com/2014/10/08/change-keyboard-language-shortcut-mac-os-x/)

**Comment by Thaina** [comment]
@bingocaller The latter

In macOS `Option+Shift` or `Cmd+Shift` cannot set as a keyboard language binding. It not activation key in macOS unlike in Windows

**Comment by bingocaller** [comment]
Ah, I didn't realise that! 🙂 
Well, I guess it isn't going be trivial, then. You would probably have to set it up to do a `shell_command` (see [caps_lock_enhancement.json](https://github.com/pqrs-org/KE-complex_modifications/blob/master/docs/json/caps_lock_enhancement.json#L608) for reference), which in turn cycles the keyboard layouts see.
I did a bit of digging of how to do that programatically, and [this Stack Overflow](https://stackoverflow.com/questions/23729704/change-osx-keyboard-layoutinput-source-programmatically-via-terminal-or-appl) answer was the only thing I could find. It isn't exactly the most direct route, but might be what you're looking for or could at least help you on your way.

**Comment by apm1467** [comment]
This can be indeed trivial. Just set the system shortcut of changing input source to be, for example, `command + space`. Then you can easily map `option + shift` to `command + space` with Karabiner-Elements. So every time you tap `option + shift`, the system will actually receive `command + space` and change the input source.

This can however break other shorts that uses the `option + shift` combination. You won't be able to use "Paste and match style" (`shift + option + command + v`) for example, since the system will receive `command + space + v`.
