### ISSUE TITLE
No way to determine if Alfred is opened

### ISSUE THREAD

**Issue by tbrodbeck** [pqrs-org/KE-complex_modifications#608]
Correct me if I'm wrong, but I cannot find a way to determine if Alfred (or Spotlight or Launchpad etc) is currently visible or not. 
The issue is that I want to implement vim key bindings to scroll down and up in my pdf reader. But even when I define my keybinds (of `hjkl`) with this condition:
```
"bundle_identifiers": [
     "^com\\.readdle\\.PDFExpert-Mac$"
 ],
"type": "frontmost_application_if"
```
It cannot recognize when the frontmost_application actually is Alfred (thus I cannot type the letters `hjkl` in Alfred anymore).

**Comment by tekezo** [comment]
It's a limitation of macOS, but Alfred provides a way. (There are no way for Spotlight and Launchpad.)

If Alfred is opened by shell command instead of own hotkey, frontmost_application will be changed to `com.runningwithcrayons.Alfred`.

Assign Alfred 4 shortcut in Karabiner-Elements by following examples.

-   Example of opening app by `shell_command`.
    https://github.com/pqrs-org/KE-complex_modifications/blob/master/public/json/launch_apps.json#L7-L25
-   `shell_command` for Alfred 4.
    https://github.com/pqrs-org/KE-complex_modifications/blob/master/public/json/personal_tekezo_launcher_mode_v4.json#L1047

**Comment by tbrodbeck** [comment]
Thanks a lot. This way I could successfully bin my keys now!
