### ISSUE TITLE
Windows shortcuts on macOS, to use left_control instead of control?

### ISSUE THREAD

**Issue by suntong** [pqrs-org/KE-complex_modifications#814]
https://github.com/pqrs-org/KE-complex_modifications/blob/3f31bbf20906c70d880b4f156d306a549127079c/public/json/windows_shortcuts_on_macos.json#L13

Would it be OK to replace all `control` with `left_control` for all rules under "Windows shortcuts on macOS"? The main reason is to give user an escape path, when they do need those key combinations. For e.g., 

`^-C` means "Control - Break" way before it means "copy". I'd like to use `^-C` for copy but also not want to miss the ability to do "control - break". Thx!

**Comment by MuhammedZakir** [comment]
Configs like this are installed by lots of users and needs to be as general as possible. Because what you suggested may break other users' setup, I don't want to change it. Sorry! :-(

I recommend you to change it locally. Actually, that's what you should do. Because there is no "fit-for-all" modification. You should modify all rules according to your needs.

**Comment by suntong** [comment]
OK. Fair enough. thx!
